### ISSUE TITLE
Just homebridge plugin for Fermax Wi-Box?

### ISSUE THREAD

**Issue by rafacampoamor** [roscoe81/Home-Manager#8]
I'm thinking about buying a Fermax Wi-Box to be able to control my video door opener with Apple Home. 

As I see you handled to connect this to Apple HomeKit through Homebridge, I wonder if such a thing could be possible starting from this point. 

I have no problem with using a RPi instead of the official Fermax add-on if I can integrate it with my Homebridge setup. 

So, I have two questions:

1. Does this setup integrate Homebridge or do I need to connect the RPi to my main Homebridge server to get it running? 
2. Is there a Homebridge plugin within this or how does it work?

Sorry for asking so much, but I'm really interested into getting this to work and cannot find where to start. 

Thank you! 😊

**Comment by roscoe81** [comment]
I did the Fermax/Homebridge integration using my Home Manager and my Doorbell Monitor (https://github.com/roscoe81/Doorbell-Monitor). The two applications communicated via mqtt and the Fermax interface (hardware and software) was done in the Doorbell Monitor. Since I did that, my building's intercom has been upgraded to a Fermax Duox system and I no longer use the Door Monitor or Home Manager for the new system. I now use Fermax Blue and its app and it does all I need. I don't know much about wibox because it wasn't available when I did my integration. From what I see, it looks very interesting. I'm not sure of any benefit in integrating that with Apple HomeKit through Homebridge, because its app appears to have all the necessary functionality (answer calls, see the video feed, talk with the door station and open the door). One thing I found with the Fermax Blue app was that it can be controlled via Siri Shortcuts and that allowed my to open the door via Siri (which is all I would need to do via Apple HomeKit). You might find that the wibox app could do the same thing, but I can't confirm that it does. If you do decide that you want to pursue Apple HomeKit integration via Homebridge, this repo: https://github.com/duhow/wibox has some mqtt work that you could possibly use as a foundation but I won't be able to help you on that journey. However, I suggest that the most effective way of getting the necessary functionality is to go with wibox - with or without Siri Shortcuts.

**Comment by rafacampoamor** [comment]
Thank you! All that info is much appreciated. Te reason I’d like HomeKit integration is to be able to watch the camera streaming from my Mac or TV and open the door wirelessly. It’s true that the app does all of it, but I like to have all my domotics aggregated. Thank you so much. I’ll take a closer look to that repo and try to guess how far can I go without knowing nodejs 😉Have a nice holidays El 24 dic 2023, a las 2:25, Ross Fowler ***@***.***> escribió:﻿
I did the Fermax/Homebridge integration using my Home Manager and my Doorbell Monitor (https://github.com/roscoe81/Doorbell-Monitor). The two applications communicated via mqtt and the Fermax interface (hardware and software) was done in the Doorbell Monitor. Since I did that, my building's intercom has been upgraded to a Fermax Duox system and I no longer use the Door Monitor or Home Manager for the new system. I now use Fermax Blue and its app and it does all I need. I don't know much about wibox because it wasn't available when I did my integration. From what I see, it looks very interesting. I'm not sure of any benefit in integrating that with Apple HomeKit through Homebridge, because its app appears to have all the necessary functionality (answer calls, see the video feed, talk with the door station and open the door). One thing I found with the Fermax Blue app was that it can be controlled via Siri Shortcuts and that allowed my to open the door via Siri (which is all I would need to do via Apple HomeKit). You might find that the wibox app could do the same thing, but I can't confirm that it does. If you do decide that you want to pursue Apple HomeKit integration via Homebridge, this repo: https://github.com/duhow/wibox has some mqtt work that you could possibly use as a foundation but I won't be able to help you on that journey. However, I suggest that the most effective way of getting the necessary functionality is to go with wibox - with or without Siri Shortcuts.
